policy_node:
  lerobot_repo_root: /home/multimodallearning/Jing/lerobot-irl-models
  checkpoint_path: /home/multimodallearning/Jing/lerobot-irl-models/outputs/beastf/beastf_banana_checkpoint_123000/123000/pretrained_model
  dataset_root: /home/zzh/workspace/Robot_learning/datasets/fold_the_towel_all
  device: cuda
  obs_topic: beast/observation
  action_topic: beast/action
  pyzlc_name: beast_policy_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731
  seed: 42

rollout_node:
  pyzlc_name: franka_rollout_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731

  policy_name: beast
  obs_topic: beast/observation
  action_topic: beast/action
  record_enable: false
  fps: 30.0

  follower_arm: FrankaFollower
  follower_gripper: FrankaFollowerGripper
  camera_names:
    - centric_cam
    - wrist_cam
  camera_preview: false

  control_dt_s: 0.033
  gripper_speed: 0.5
  align_q: [-0.238135, -0.036628, 0.298702, -2.131368, 0.109387, 2.111649, 0.850056, 0.069985]

