policy_node:
  lerobot_repo_root: /home/multimodallearning/Jing/lerobot-irl-models
  checkpoint_path: /home/multimodallearning/Jing/checkpoints/beastf/21_3/150000/pretrained_model
  dataset_root: /home/multimodallearning/Jing/dataset/fold_the_towel_all/home/jing/zihao_zhang/fold_the_towel_all
  device: cuda
  enforce_init_pos: true
  debug_print_control_points: false
  obs_topic: beast/observation
  action_topic: beast/action
  pyzlc_name: beast_policy_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731
  seed: 42

rollout_node:
  pyzlc_name: franka_rollout_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731

  policy_name: beast
  obs_topic: beast/observation
  action_topic: beast/action
  record_enable: false
  joint_target_tolerance: 0.01
  gripper_target_tolerance: 0.01

  follower_arm: FrankaFollower
  follower_gripper: FrankaFollowerGripper
  camera_names:
    - centric_cam
    - wrist_cam
  camera_preview: false

  control_dt_s: 0.033
  gripper_speed: 0.5
  align_q: [-0.238027175526648,
   -0.03739903886903796,
   0.298479903707504,
   -2.1307362981093554,
   0.1099801990323587,
   2.1112839427259235,
   0.850087088974428]
