policy_node:
  lerobot_repo_root: /home/multimodallearning/Jing/lerobot-irl-models
  checkpoint_path: /home/multimodallearning/Jing/lerobot-irl-models/outputs/030000/pretrained_model
  stats_data_dir: /home/multimodallearning/Jing/lerobot-irl-models/data/banana_beso_all
  dataset_repo_id: banana_beso_all
  device: cuda
  use_non_ema: false
  sampling_steps: 10
  obs_topic: beso/observation
  action_topic: beso/action
  pyzlc_name: beso_policy_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731
  seed: 42

rollout_node:
  pyzlc_name: franka_rollout_node
  pyzlc_host: 141.3.53.25
  pyzlc_group: 224.0.0.1
  pyzlc_group_name: realrobot_rollout
  pyzlc_group_port: 7731

  policy_name: beso
  obs_topic: beso/observation
  action_topic: beso/action
  record_enable: false
  task: ""
  fps: 30.0

  follower_arm: FrankaFollower
  follower_gripper: FrankaFollowerGripper
  camera_names:
    - centric_cam
    - wrist_cam
  camera_preview: false

  control_dt_s: 0.033
  gripper_speed: 0.5
  align_q: [-0.838027175526648, 0.23739903886903796, 0.998479903707504, -1.9307362981093554, -0.1399801990323587, 2.0812839427259235, 1.0100087088974428]
